version: '3'
services:
  api:
    build: ./docker/apiv1
    container_name: rpooli-api
    ports:
      - ${RPOOLI_API_PORT}:8080
      - 1100:1100
    volumes:
      - ./webapp/target/rpooli-${RPOOLI_VERSION}-SNAPSHOT.war:/opt/jetty/webapps/rpooli.war:ro
