apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rpooli-build
spec:
  containers:
   - name: maven
     image: maven:3-openjdk-8
     command:
     - cat
     tty: true	
   - name: rpooli-tests
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rpooli-tests
     command:
     - cat
     tty: true