apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rpooli-build
spec:
  containers:
  - name: rpooli-build
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rpooli-build
    command:
    - cat
    tty: true
