#%RAML 0.8
---
title: RPooli API
baseUri: ${baseUri}/api/{version}
version: v1
mediaType:  application/json

documentation:
  - title: RPooli API
    content: |
      <pre>
       ___ ___          _ _ 
      | _ \ _ \___  ___| (_)
      |   /  _/ _ \/ _ \ | |
      |_|_\_| \___/\___/_|_|
      </pre>
      _A pool of R nodes, exposed over RMI and managed over HTTP_

schemas:
 - error.json:  !include schema/error.json
 - pool.json:   !include schema/pool.json
 - node.json:   !include schema/node.json
 - nodes.json:  !include schema/nodes.json
 - conf-r.json: !include schema/conf-r.json

traits:
 - erroring:
     usage: Defines errors that yield a JSON response body.
     responses:
       400:
         body:
           schema: error.json
       500:
         body:
           schema: error.json

/pool:
  is: [ erroring ]
  description: Manage the pool of RServi nodes.
  get:
    description: Retrieve information about the pool.
    responses:
      200:
        body:
          schema: pool.json

/nodes:
  is: [ erroring ]
  description: Manage the RServi nodes.
  get:
    description: Retrieve the list of nodes.
    responses:
      200:
        body:
          schema: nodes.json
  /{nodeId}:
    is: [ erroring ]
    description: Manage a single RServi node.
    uriParameters:
      nodeId:
        type: string
        required: true
    get:
      description: Retrieve a single node.
      responses:
        200:
          body:
            schema: node.json
        404:
          description: The node ID doesn't exist.
          body:
            schema: error.json
    delete:
      description: Evict a node
      queryParameters:
        kill:
          description: If true, the node is immediately evicted. 
          type: boolean
          required: false
          default: false
      responses:
        204:
          description: The node has been evicted.
    /console:
      is: [ erroring ]
      description: Control the debug console.
      post:
        description: Enable the debug console.
        responses:
          204:
            description: The debug console is active.
      delete:
        description: The debug console is inactive.
        responses:
          204:
            description: The command has been successfully executed.
  /test:
    is: [ erroring ]
    description: Simulate client actions.
    post:
      description: Acquire a node from the pool.
      responses:
        204:
          description: A node has been acquired.
    delete:
      description: Release all the acquired nodes to the pool.
      responses:
        204:
          description: All acquired nodes have been released.

/config:
  is: [ erroring ]
  description: Configure RPooli.
  /r:
    is: [ erroring ]
    description: R/Rj nodes configuration.
    get:
      description: Retrieve the current configuration.
      responses:
        200:
          body:
            schema: conf-r.json
    put:
      description: Configure the parameters to start R.
      queryParameters:
        save:
          description: If true, the configuration will be applied and saved, otherwise it will only be applied.
          type: boolean
          required: false
          default: false
      body:
        schema: conf-r.json
      responses:
        204:
          description: The configuration has been accepted.
    /default:
      is: [ erroring ]
      description: The default configuration.
      get:
        description: Get the default configuration.
        responses:
          200:
            body:
              schema: conf-r.json
