#%RAML 0.8
---
title: RPooli API
baseUri: ${baseUri}/api/{version}
version: v1
mediaType:  application/json

documentation:
  - title: RPooli API
    content: |
      <pre>
       ___ ___          _ _ 
      | _ \ _ \___  ___| (_)
      |   /  _/ _ \/ _ \ | |
      |_|_\_| \___/\___/_|_|
      </pre>
      _A pool of R nodes, exposed over RMI and managed over HTTP_

schemas:
 - pool.json:         !include schema/pool.json
 - node.json:         !include schema/node.json
 - nodes.json:        !include schema/nodes.json

traits:
 - async-resource:
     usage: Apply this to any method that needs to be asynchronous

/pool:
  description: Manage the pool of RServi nodes
  get:
    description: Retrieve information about the pool
    responses:
      200:
        body:
          application/json:
            schema: pool.json

/nodes:
  description: Manage the RServi nodes
  get:
    description: Retrieve the list of nodes
    responses:
      200:
        body:
          schema: nodes.json
  /{nodeId}:
    description: Manage a single RServi node
    uriParameters:
      nodeId:
        type: string
        required: true
    get:
      description: Retrieve a single node
      responses:
        200:
          body:
            schema: node.json
        404:
          description: The node ID doesn't exist
    delete:
      description: Evict a node
      queryParameters:
        kill:
          type: boolean
          required: false
          default: false
      responses:
        204:
          description: The node has been evicted
    /console:
      description: Control the debug console
      post:
        description: Enable the debug console
        responses:
          204:
            description: The debug console is active
      delete:
        description: The debug console is inactive
        responses:
          204:
            description: The command has been successfully executed.
  /test:
    description: Simulate client actions
    post:
      description: Acquire a node from the pool
      responses:
        204:
          description: A node has been acquired
    delete:
      description: Release all the acquired nodes to the pool
      responses:
        204:
          description: All acquired nodes have been released
